Repository terraform-docs/gh-actions, pull requests merged in 2024-09, with the labels that each got.

#138 Adding git-sub-dir
  CONTRIBUTING.md
  README.md
  action.yml
  src/docker-entrypoint.sh
Labels: size/M

#141 Bump to v1.2.2
  README.md
  action.yml
Labels: size/S

#142 Add section about creating a release to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: size/XS

#144 chore: revert the action name back for now
  action.yml
  examples/tf12_atlantis/README.md
  examples/tf12_basic/README.md
  examples/tf12_config/README.md
  examples/tf12_find/USAGE.md
  examples/tf12_find/modules/tf12_find_submodules/USAGE.md
  examples/tf12_inject/README.md
Labels: size/S
